# Generated by Django 4.2.15 on 2025-03-26 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endpoint',
            name='id',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='user',
        ),
        migrations.AddField(
            model_name='endpoint',
            name='endpoint_id',
            field=models.CharField(default=-1, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='endpoint_status',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='user_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='components.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Memory_Diagnostics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mem_percent_usage', models.FloatField()),
                ('mem_GB_usage', models.IntegerField()),
                ('endpoint_id', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='components.endpoint')),
            ],
        ),
        migrations.CreateModel(
            name='Disk_Diagnostics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disk_percent_usage', models.FloatField()),
                ('disk_GB_usage', models.IntegerField()),
                ('endpoint_id', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='components.endpoint')),
            ],
        ),
        migrations.CreateModel(
            name='CPU_Diagnostics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_percent_usage', models.FloatField()),
                ('cpu_GB_usage', models.IntegerField()),
                ('endpoint_id', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='components.endpoint')),
            ],
        ),
    ]
