# Generated by Django 4.2.15 on 2025-04-11 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0002_remove_endpoint_id_remove_endpoint_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cpu_diagnostics",
            name="endpoint_id",
        ),
    ]
