# Generated by Django 4.2.15 on 2025-04-18 18:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_remove_endpoint_id_remove_endpoint_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memory_diagnostics',
            old_name='mem_percent_usage',
            new_name='memory_percent_usage',
        ),
        migrations.RemoveField(
            model_name='cpu_diagnostics',
            name='cpu_GB_usage',
        ),
        migrations.RemoveField(
            model_name='cpu_diagnostics',
            name='endpoint_id',
        ),
        migrations.RemoveField(
            model_name='disk_diagnostics',
            name='endpoint_id',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='endpoint_status',
        ),
        migrations.RemoveField(
            model_name='memory_diagnostics',
            name='endpoint_id',
        ),
        migrations.RemoveField(
            model_name='memory_diagnostics',
            name='mem_GB_usage',
        ),
        migrations.AddField(
            model_name='cpu_diagnostics',
            name='event_time',
            field=models.TimeField(blank=True, default=datetime.time(9, 0), null=True),
        ),
        migrations.AddField(
            model_name='disk_diagnostics',
            name='disk_GB_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='disk_diagnostics',
            name='event_time',
            field=models.TimeField(blank=True, default=datetime.time(9, 0), null=True),
        ),
        migrations.AddField(
            model_name='memory_diagnostics',
            name='event_time',
            field=models.TimeField(blank=True, default=datetime.time(9, 0), null=True),
        ),
        migrations.AddField(
            model_name='memory_diagnostics',
            name='memory_GB_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='memory_diagnostics',
            name='memory_GB_usage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cpu_diagnostics',
            name='cpu_percent_usage',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='disk_diagnostics',
            name='disk_GB_usage',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='Endpoint_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_status', models.SmallIntegerField(null=True)),
                ('event_time', models.TimeField(blank=True, default=datetime.time(9, 0), null=True)),
                ('endpoint_id', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='components.endpoint')),
            ],
        ),
    ]
