# Generated by Django 4.2.15 on 2025-04-18 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_rename_mem_percent_usage_memory_diagnostics_memory_percent_usage_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Endpoint_Log',
            new_name='Endpoint_Logs',
        ),
    ]
