# Generated by Django 4.2.15 on 2025-04-11 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0003_remove_cpu_diagnostics_endpoint_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cpu_diagnostics",
            name="cpu_GB_usage",
        ),
        migrations.AddField(
            model_name="cpu_diagnostics",
            name="event_time",
            field=models.TimeField(blank=True, default=datetime.time(9, 0), null=True),
        ),
    ]
