# Generated by Django 4.2.15 on 2025-04-12 00:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0004_remove_cpu_diagnostics_cpu_gb_usage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="disk_diagnostics",
            name="endpoint_id",
        ),
        migrations.RemoveField(
            model_name="memory_diagnostics",
            name="endpoint_id",
        ),
        migrations.AddField(
            model_name="disk_diagnostics",
            name="event_time",
            field=models.TimeField(blank=True, default=datetime.time(9, 0), null=True),
        ),
        migrations.AddField(
            model_name="memory_diagnostics",
            name="event_time",
            field=models.TimeField(blank=True, default=datetime.time(9, 0), null=True),
        ),
    ]
