# Generated by Django 4.2.15 on 2025-04-18 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_rename_endpoint_log_endpoint_logs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Endpoint_Logs',
            new_name='Endpoint_Log22424s',
        ),
    ]
