# Generated by Django 4.2.15 on 2025-04-18 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0005_rename_endpoint_logs_endpoint_log22424s'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Endpoint_Log22424s',
            new_name='Endpoint_Log',
        ),
    ]
