# Generated by Django 4.2.15 on 2025-04-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0005_remove_disk_diagnostics_endpoint_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="memory_diagnostics",
            old_name="mem_percent_usage",
            new_name="memory_percent_usage",
        ),
        migrations.RemoveField(
            model_name="memory_diagnostics",
            name="mem_GB_usage",
        ),
        migrations.AddField(
            model_name="memory_diagnostics",
            name="memory_GB_total",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="memory_diagnostics",
            name="memory_GB_usage",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="cpu_diagnostics",
            name="cpu_percent_usage",
            field=models.FloatField(blank=True),
        ),
    ]
