# Generated by Django 4.2.15 on 2025-04-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0006_rename_endpoint_log22424s_endpoint_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endpoint',
            name='endpoint_name',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='endpoint_id',
            field=models.CharField(default=-1, max_length=60, primary_key=True, serialize=False),
        ),
    ]
