# Generated by Django 4.2.15 on 2025-04-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "components",
            "0006_rename_mem_percent_usage_memory_diagnostics_memory_percent_usage_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="disk_diagnostics",
            name="disk_GB_total",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="disk_diagnostics",
            name="disk_GB_usage",
            field=models.FloatField(default=0.0),
        ),
    ]
