# Generated by Django 4.2.15 on 2025-04-18 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0007_remove_endpoint_endpoint_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='endpoint_name',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='user_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='components.user'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='endpoint_id',
            field=models.CharField(default=-1, max_length=32, primary_key=True, serialize=False),
        ),
    ]
