# Generated by Django 4.2.15 on 2025-04-13 02:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0007_disk_diagnostics_disk_gb_total_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="endpoint",
            name="endpoint_name",
        ),
        migrations.RemoveField(
            model_name="endpoint",
            name="endpoint_status",
        ),
        migrations.RemoveField(
            model_name="endpoint",
            name="user_id",
        ),
        migrations.CreateModel(
            name="Endpoint_Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint_status", models.SmallIntegerField(null=True)),
                (
                    "event_time",
                    models.TimeField(
                        blank=True, default=datetime.time(9, 0), null=True
                    ),
                ),
                (
                    "endpoint_id",
                    models.ForeignKey(
                        default=-1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="components.user",
                    ),
                ),
            ],
        ),
    ]
