# Generated by Django 4.2.15 on 2025-04-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0008_endpoint_endpoint_name_endpoint_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='endpoint_status',
            field=models.SmallIntegerField(default=1),
        ),
    ]
