# Generated by Django 4.2.15 on 2025-04-20 06:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0008_endpoint_endpoint_name_endpoint_user_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cpu_diagnostics",
            name="event_time",
            field=models.DateTimeField(
                blank=True, default=datetime.time(9, 0), null=True
            ),
        ),
        migrations.AlterField(
            model_name="disk_diagnostics",
            name="event_time",
            field=models.DateTimeField(
                blank=True, default=datetime.time(9, 0), null=True
            ),
        ),
        migrations.AlterField(
            model_name="endpoint_log",
            name="event_time",
            field=models.DateTimeField(
                blank=True, default=datetime.time(9, 0), null=True
            ),
        ),
        migrations.AlterField(
            model_name="memory_diagnostics",
            name="event_time",
            field=models.DateTimeField(
                blank=True, default=datetime.time(9, 0), null=True
            ),
        ),
    ]
