# Generated by Django 4.2.15 on 2025-04-13 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0008_remove_endpoint_endpoint_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="endpoint",
            name="endpoint_id",
            field=models.CharField(
                default=-1, max_length=60, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="endpoint_log",
            name="endpoint_id",
            field=models.ForeignKey(
                default=-1,
                on_delete=django.db.models.deletion.CASCADE,
                to="components.endpoint",
            ),
        ),
    ]
