# Generated by Django 4.2.15 on 2025-04-18 02:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0009_alter_endpoint_endpoint_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cpu_diagnostics",
            name="event_time",
            field=models.TimeField(blank=True, default=datetime.time(9, 0)),
        ),
    ]
