# Generated by Django 4.2.15 on 2025-04-21 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0009_alter_cpu_diagnostics_event_time_and_more'),
        ('components', '0009_endpoint_endpoint_status'),
    ]

    operations = [
    ]
