# Generated by Django 4.2.15 on 2025-04-18 03:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0011_alter_cpu_diagnostics_event_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disk_diagnostics",
            name="event_time",
            field=models.DateTimeField(
                blank=True, default=datetime.time(9, 0), null=True
            ),
        ),
        migrations.AlterField(
            model_name="endpoint_log",
            name="event_time",
            field=models.DateTimeField(
                blank=True, default=datetime.time(9, 0), null=True
            ),
        ),
        migrations.AlterField(
            model_name="memory_diagnostics",
            name="event_time",
            field=models.DateTimeField(
                blank=True, default=datetime.time(9, 0), null=True
            ),
        ),
    ]
